version: '3'

services:
  database:
    image: postgres:9.6
    ports:
      - ${PG_PORT-5432}:5432
    environment:
      - "POSTGRES_USER=redminesync"
      - "POSTGRES_PASSWORD=redminesync"
      - POSTGRES_DB=postgres
    volumes:
      - postgres_redminesync:/var/lib/postgresql/data:delegated

  php:
    build:
      context: ./docker/php-fpm
    user: ${UID:-1000}:${GID:-1000}
    depends_on:
      - database
    volumes:
      - .:/var/www
      - ${HOME}/.composer:/.composer
    environment:
      - "COMPOSER_MEMORY_LIMIT=-1"

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    ports:
      - ${HTTP_PORT-80}:80
      - ${HTTPS_PORT-443}:443
    depends_on:
      - php

  encore:
    image: node:10-alpine
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - .:/app
      - ${HOME}/.yarn:/.yarn
      - ${HOME}/.yarnrc:/.yarnrc
      - ${HOME}/.cache/yarn:/.cache/yarn
    working_dir: /app

volumes:
  postgres_redminesync:
    external: true
